volumes:
  grafana_data:

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=sonora
      - GF_SECURITY_ADMIN_PASSWORD=sonoramusic
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    networks:
      - monitoring
    external_links:
      - prometheus:prometheus

networks:
  monitoring:
    external: true
    name: lidarrapimetadata_monitoring
