global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'lidarr_api'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['metadata-api:5001']
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 